/// <reference path="Magnesium.ts" />

namespace Magnesium {
  export class MgPhysicalDeviceFeatures {
    robustBufferAccess : boolean;
    fullDrawIndexUint32 : boolean;
    imageCubeArray : boolean;
    independentBlend : boolean;
    geometryShader : boolean;
    tessellationShader : boolean;
    sampleRateShading : boolean;
    dualSrcBlend : boolean;
    logicOp : boolean;
    multiDrawIndirect : boolean;
    drawIndirectFirstInstance : boolean;
    depthClamp : boolean;
    depthBiasClamp : boolean;
    fillModeNonSolid : boolean;
    depthBounds : boolean;
    wideLines : boolean;
    largePoints : boolean;
    alphaToOne : boolean;
    multiViewport : boolean;
    samplerAnisotropy : boolean;
    textureCompressionETC2 : boolean;
    textureCompressionASTC_LDR : boolean;
    textureCompressionBC : boolean;
    occlusionQueryPrecise : boolean;
    pipelineStatisticsQuery : boolean;
    vertexPipelineStoresAndAtomics : boolean;
    fragmentStoresAndAtomics : boolean;
    shaderTessellationAndGeometryPointSize : boolean;
    shaderImageGatherExtended : boolean;
    shaderStorageImageExtendedFormats : boolean;
    shaderStorageImageMultisample : boolean;
    shaderStorageImageReadWithoutFormat : boolean;
    shaderStorageImageWriteWithoutFormat : boolean;
    shaderUniformBufferArrayDynamicIndexing : boolean;
    shaderSampledImageArrayDynamicIndexing : boolean;
    shaderStorageBufferArrayDynamicIndexing : boolean;
    shaderStorageImageArrayDynamicIndexing : boolean;
    shaderClipDistance : boolean;
    shaderCullDistance : boolean;
    shaderFloat64 : boolean;
    shaderInt64 : boolean;
    shaderInt16 : boolean;
    shaderResourceResidency : boolean;
    shaderResourceMinLod : boolean;
    sparseBinding : boolean;
    sparseResidencyBuffer : boolean;
    sparseResidencyImage2D : boolean;
    sparseResidencyImage3D : boolean;
    sparseResidency2Samples : boolean;
    sparseResidency4Samples : boolean;
    sparseResidency8Samples : boolean;
    sparseResidency16Samples : boolean;
    sparseResidencyAliased : boolean;
    letiableMultisampleRate : boolean;
    inheritedQueries : boolean;
  }
}