namespace Magnesium {
	export enum WGLVertexAttributeType	{
		BYTE,
		UNSIGNED_BYTE,
		SHORT,
		UNSIGNED_SHORT,
		INT,
		UNSIGNED_INT,
		FLOAT,
		DOUBLE,
		HALF_FLOAT,
		FIXED,
		UNSIGNED_INT_2101010_REV,
		INT_2101010_REV
	}
}